language: csharp
mono:
  - latest

os:
  - linux

addons:
  apt:
    sources:
    - deadsnakes
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - time
    - swig
    - clang-3.7
    - g++-5
    - gcc-5
    - 
install:
  - nuget restore TestSWIG.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

cache: apt

script:
  - swig -c++ -csharp -namespace LibraryNamespace -I./CPP/Library/ -outdir CSharp/CSharpLibrary/ -o CSharp/CSharpWrapper/SimpleAPIWrapper.cxx CSharp/SimplifiedAPI.i
  - export CXX=`which clang++-3.7` CC=`which clang-3.7`;
  - cmake -DCMAKE_BUILD_TYPE="Release" -G "Unix Makefiles" ./
  - make -j2
  - make release -j2
  - make install
  - ls ./Build/
  - xbuild /p:Configuration=Release ./CSharp/CSharpLibrary/CSharpLibrary.csproj
  - xbuild /p:Configuration=Release ./CSharp/Tests/Tests.csproj
  - ls ./Build/
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Build/Release/CSharpTests.dll

