language: csharp

mono:
  - latest

os:
  - linux

addons:
  apt:
    sources:
    - deadsnakes
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - time
    - swig
    - gcc-4.8
    - g++-4.8

install:
  - nuget restore TestSWIG.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - ls testrunner/NUnit.Runners.2.6.4/tools/

script:
  - swig -c++ -csharp -namespace LibraryNamespace -I./CPP/Library/ -outdir CSharp/CSharpLibrary/ -o CSharp/CSharpWrapper/SimpleAPIWrapper.cxx CSharp/SimplifiedAPI.i
  - export CC=/usr/bin/gcc-4.8
  - export CXX=/usr/bin/g++-4.8
  - cmake -DCMAKE_BUILD_TYPE="Release" -G "Unix Makefiles" ./
  - make -j1
  - ls ./Build/Release/
  - xbuild /p:Configuration=Release ./CSharp/CSharpLibrary/CSharpLibrary.csproj
  - xbuild /p:Configuration=Release ./CSharp/Tests/Tests.csproj
  - ls ./Build/Release/
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CSharp/Tests/Tests.csproj /config:Release

