version: 2.0.{build}

environment:
  matrix:
#    - VSVER: Visual Studio 11 2012 Win64
#    - VSVER: Visual Studio 12 2013 Win64
    - VSVER: Visual Studio 14 2015 Win64

platform:
#  - x86
  - x64

configuration:
  - Release

install:
    - choco install cmake
    - choco upgrade cmake
    - choco install nunit
    - choco upgrade nunit
    - choco install swig
    - choco upgrade swig
    - git submodule -q update --init

cache: 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml 
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Users\appveyor\AppData\Local\Temp\chocolatey

before_build:
    - nuget restore TestSWIG.sln
    - swig -c++ -csharp -namespace LibraryNamespace -I./CPP/Library/ -outdir CSharp/CSharpLibrary/ -o CSharp/CSharpWrapper/SimpleAPIWrapper.cxx CSharp/SimplifiedAPI.i

build:
    project: TestSWIG.sln

after_build: 
    - ls C:\projects\testswig\build\
    - msbuild C:\projects\testswig\CSharp\CSharpLibrary\CSharpLibrary.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild C:\projects\testswig\CSharp\Tests\Tests.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - ls C:\projects\testswig\build\release\


test_script:
 - ps: if($env:PLATFORM -eq "x86") { nunit-console-x86 /config:Release C:\projects\testswig\CSharp\Tests\Tests.csproj }
 - ps: if( $env:PLATFORM -eq "x64" ) { nunit-console /config:Release C:\projects\testswig\CSharp\Tests\Tests.csproj }