//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace LibraryNamespace {

public class A : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal A(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(A obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~A() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          CSharpWrapperPINVOKE.delete_A(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void SetName(string n) {
    if (SwigDerivedClassHasMethod("SetName", swigMethodTypes0)) CSharpWrapperPINVOKE.A_SetNameSwigExplicitA(swigCPtr, n); else CSharpWrapperPINVOKE.A_SetName(swigCPtr, n);
    if (CSharpWrapperPINVOKE.SWIGPendingException.Pending) throw CSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string SayHello() {
    string ret = (SwigDerivedClassHasMethod("SayHello", swigMethodTypes1) ? CSharpWrapperPINVOKE.A_SayHelloSwigExplicitA(swigCPtr) : CSharpWrapperPINVOKE.A_SayHello(swigCPtr));
    if (CSharpWrapperPINVOKE.SWIGPendingException.Pending) throw CSharpWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public A() : this(CSharpWrapperPINVOKE.new_A(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("SetName", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateA_0(SwigDirectorSetName);
    if (SwigDerivedClassHasMethod("SayHello", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateA_1(SwigDirectorSayHello);
    CSharpWrapperPINVOKE.A_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(A));
    return hasDerivedMethod;
  }

  private void SwigDirectorSetName(string n) {
    SetName(n);
  }

  private string SwigDirectorSayHello() {
    return SayHello();
  }

  public delegate void SwigDelegateA_0(string n);
  public delegate string SwigDelegateA_1();

  private SwigDelegateA_0 swigDelegate0;
  private SwigDelegateA_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(string) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
}

}
