//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace LibraryNamespace {

public class B : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal B(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(B obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~B() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          LibraryPINVOKE.delete_B(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void SetA(A p) {
    if (SwigDerivedClassHasMethod("SetA", swigMethodTypes0)) LibraryPINVOKE.B_SetASwigExplicitB(swigCPtr, A.getCPtr(p)); else LibraryPINVOKE.B_SetA(swigCPtr, A.getCPtr(p));
    if (LibraryPINVOKE.SWIGPendingException.Pending) throw LibraryPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string CallA() {
    string ret = (SwigDerivedClassHasMethod("CallA", swigMethodTypes1) ? LibraryPINVOKE.B_CallASwigExplicitB(swigCPtr) : LibraryPINVOKE.B_CallA(swigCPtr));
    if (LibraryPINVOKE.SWIGPendingException.Pending) throw LibraryPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public B() : this(LibraryPINVOKE.new_B(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("SetA", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateB_0(SwigDirectorSetA);
    if (SwigDerivedClassHasMethod("CallA", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateB_1(SwigDirectorCallA);
    LibraryPINVOKE.B_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(B));
    return hasDerivedMethod;
  }

  private void SwigDirectorSetA(global::System.IntPtr p) {
    SetA(new A(p, false));
  }

  private string SwigDirectorCallA() {
    return CallA();
  }

  public delegate void SwigDelegateB_0(global::System.IntPtr p);
  public delegate string SwigDelegateB_1();

  private SwigDelegateB_0 swigDelegate0;
  private SwigDelegateB_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(A) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
}

}
